### PR TITLE
Fail build if Scalafmt reports errors

### PR DESCRIPTION
**Pull request by jozic**
# Description
This is related to #42 . Currently scalafmt-dynamic reports errors to reporter, but doesn't indicate the error otherwise, so mvn_scalafmt may log tons of errors and then successfully finishes the build.
here's example

```shell
➜  mvn_scalafmt git:(fail-on-errors) ✗ mvn org.antipathy:mvn-scalafmt_2.12:format
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.antipathy:mvn-scalafmt_2.12:maven-plugin:1.0.2-SNAPSHOT
[WARNING] 'artifactId' contains an expression but should be a constant. @ org.antipathy:mvn-scalafmt_${version.scala.major}:1.0.2-SNAPSHOT, /home/jozic/projects/github/mvn_scalafmt/pom.xml, line 5, column 17
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] Inspecting build with total of 1 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 1 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[INFO] 
[INFO] ------------------< org.antipathy:mvn-scalafmt_2.12 >-------------------
[INFO] Building ScalaFmt Maven Plugin (2.12) 1.0.2-SNAPSHOT
[INFO] ----------------------------[ maven-plugin ]----------------------------
[INFO] 
[INFO] --- mvn-scalafmt_2.12:1.0.0:format (default-cli) @ mvn-scalafmt_2.12 ---
[ERROR] ScalaFmt: error: /home/jozic/projects/github/mvn_scalafmt/.scalafmt.conf: missing setting 'version'. To fix this problem, add the following line to .scalafmt.conf: 'version=2.0.1'.
[ERROR] ScalaFmt: error: /home/jozic/projects/github/mvn_scalafmt/.scalafmt.conf: missing setting 'version'. To fix this problem, add the following line to .scalafmt.conf: 'version=2.0.1'.
[ERROR] ScalaFmt: error: /home/jozic/projects/github/mvn_scalafmt/.scalafmt.conf: missing setting 'version'. To fix this problem, add the following line to .scalafmt.conf: 'version=2.0.1'.
[ERROR] ScalaFmt: error: /home/jozic/projects/github/mvn_scalafmt/.scalafmt.conf: missing setting 'version'. To fix this problem, add the following line to .scalafmt.conf: 'version=2.0.1'.
[ERROR] ScalaFmt: error: /home/jozic/projects/github/mvn_scalafmt/.scalafmt.conf: missing setting 'version'. To fix this problem, add the following line to .scalafmt.conf: 'version=2.0.1'.
[ERROR] ScalaFmt: error: /home/jozic/projects/github/mvn_scalafmt/.scalafmt.conf: missing setting 'version'. To fix this problem, add the following line to .scalafmt.conf: 'version=2.0.1'.
[ERROR] ScalaFmt: error: /home/jozic/projects/github/mvn_scalafmt/.scalafmt.conf: missing setting 'version'. To fix this problem, add the following line to .scalafmt.conf: 'version=2.0.1'.
[ERROR] ScalaFmt: error: /home/jozic/projects/github/mvn_scalafmt/.scalafmt.conf: missing setting 'version'. To fix this problem, add the following line to .scalafmt.conf: 'version=2.0.1'.
[ERROR] ScalaFmt: error: /home/jozic/projects/github/mvn_scalafmt/.scalafmt.conf: missing setting 'version'. To fix this problem, add the following line to .scalafmt.conf: 'version=2.0.1'.
[ERROR] ScalaFmt: error: /home/jozic/projects/github/mvn_scalafmt/.scalafmt.conf: missing setting 'version'. To fix this problem, add the following line to .scalafmt.conf: 'version=2.0.1'.
[ERROR] ScalaFmt: error: /home/jozic/projects/github/mvn_scalafmt/.scalafmt.conf: missing setting 'version'. To fix this problem, add the following line to .scalafmt.conf: 'version=2.0.1'.
[ERROR] ScalaFmt: error: /home/jozic/projects/github/mvn_scalafmt/.scalafmt.conf: missing setting 'version'. To fix this problem, add the following line to .scalafmt.conf: 'version=2.0.1'.
[ERROR] ScalaFmt: error: /home/jozic/projects/github/mvn_scalafmt/.scalafmt.conf: missing setting 'version'. To fix this problem, add the following line to .scalafmt.conf: 'version=2.0.1'.
[ERROR] ScalaFmt: error: /home/jozic/projects/github/mvn_scalafmt/.scalafmt.conf: missing setting 'version'. To fix this problem, add the following line to .scalafmt.conf: 'version=2.0.1'.
[ERROR] ScalaFmt: error: /home/jozic/projects/github/mvn_scalafmt/.scalafmt.conf: missing setting 'version'. To fix this problem, add the following line to .scalafmt.conf: 'version=2.0.1'.
[ERROR] ScalaFmt: error: /home/jozic/projects/github/mvn_scalafmt/.scalafmt.conf: missing setting 'version'. To fix this problem, add the following line to .scalafmt.conf: 'version=2.0.1'.
[ERROR] ScalaFmt: error: /home/jozic/projects/github/mvn_scalafmt/.scalafmt.conf: missing setting 'version'. To fix this problem, add the following line to .scalafmt.conf: 'version=2.0.1'.
[ERROR] ScalaFmt: error: /home/jozic/projects/github/mvn_scalafmt/.scalafmt.conf: missing setting 'version'. To fix this problem, add the following line to .scalafmt.conf: 'version=2.0.1'.
[ERROR] ScalaFmt: error: /home/jozic/projects/github/mvn_scalafmt/.scalafmt.conf: missing setting 'version'. To fix this problem, add the following line to .scalafmt.conf: 'version=2.0.1'.
[ERROR] ScalaFmt: error: /home/jozic/projects/github/mvn_scalafmt/.scalafmt.conf: missing setting 'version'. To fix this problem, add the following line to .scalafmt.conf: 'version=2.0.1'.
[ERROR] ScalaFmt: error: /home/jozic/projects/github/mvn_scalafmt/.scalafmt.conf: missing setting 'version'. To fix this problem, add the following line to .scalafmt.conf: 'version=2.0.1'.
[ERROR] ScalaFmt: error: /home/jozic/projects/github/mvn_scalafmt/.scalafmt.conf: missing setting 'version'. To fix this problem, add the following line to .scalafmt.conf: 'version=2.0.1'.
[ERROR] ScalaFmt: error: /home/jozic/projects/github/mvn_scalafmt/.scalafmt.conf: missing setting 'version'. To fix this problem, add the following line to .scalafmt.conf: 'version=2.0.1'.
[ERROR] ScalaFmt: error: /home/jozic/projects/github/mvn_scalafmt/.scalafmt.conf: missing setting 'version'. To fix this problem, add the following line to .scalafmt.conf: 'version=2.0.1'.
[ERROR] ScalaFmt: error: /home/jozic/projects/github/mvn_scalafmt/.scalafmt.conf: missing setting 'version'. To fix this problem, add the following line to .scalafmt.conf: 'version=2.0.1'.
[ERROR] ScalaFmt: error: /home/jozic/projects/github/mvn_scalafmt/.scalafmt.conf: missing setting 'version'. To fix this problem, add the following line to .scalafmt.conf: 'version=2.0.1'.
[ERROR] ScalaFmt: error: /home/jozic/projects/github/mvn_scalafmt/.scalafmt.conf: missing setting 'version'. To fix this problem, add the following line to .scalafmt.conf: 'version=2.0.1'.
[ERROR] ScalaFmt: error: /home/jozic/projects/github/mvn_scalafmt/.scalafmt.conf: missing setting 'version'. To fix this problem, add the following line to .scalafmt.conf: 'version=2.0.1'.
[INFO] Scalafmt results: 0 of 28 were unformatted
Details:
ConfigFileValidator.scala: Correctly formatted: 
Validator.scala: Correctly formatted: 
ScalaFormatter.scala: Correctly formatted: 
SourceFileSequenceBuilder.scala: Correctly formatted: 
Builder.scala: Correctly formatted: 
LocalConfigBuilder.scala: Correctly formatted: 
FilesSummaryBuilder.scala: Correctly formatted: 
Formatter.scala: Correctly formatted: 
SourceFileFormatter.scala: Correctly formatted: 
RemoteConfigWriter.scala: Correctly formatted: 
TestResultLogWriter.scala: Correctly formatted: 
Reader.scala: Correctly formatted: 
RemoteConfigReader.scala: Correctly formatted: 
Writer.scala: Correctly formatted: 
FormattedFilesWriter.scala: Correctly formatted: 
Summary.scala: Correctly formatted: 
FileSummaryRequest.scala: Correctly formatted: 
FileSummary.scala: Correctly formatted: 
RemoteConfig.scala: Correctly formatted: 
FormatResult.scala: Correctly formatted: 
MavenLogReporter.scala: Correctly formatted: 
ConfigFileValidatorSpec.scala: Correctly formatted: 
SourceFileSequenceBuilderSpec.scala: Correctly formatted: 
LocalConfigBuilderSpec.scala: Correctly formatted: 
SourceFileFormatterSpec.scala: Correctly formatted: 
FormattedFilesWriterSpec.scala: Correctly formatted: 
RemoteConfigReaderSpec.scala: Correctly formatted: 
RemoteConfigWriterSpec.scala: Correctly formatted: 
     
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.172 s
[INFO] Finished at: 2019-09-30T07:25:46-04:00
[INFO] ------------------------------------------------------------------------
```

with this fix, it's gonna be like

```shell
➜  mvn_scalafmt git:(fail-on-errors) ✗ mvn org.antipathy:mvn-scalafmt_2.12:format
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.antipathy:mvn-scalafmt_2.12:maven-plugin:1.0.2-SNAPSHOT
[WARNING] 'artifactId' contains an expression but should be a constant. @ org.antipathy:mvn-scalafmt_${version.scala.major}:1.0.2-SNAPSHOT, /home/jozic/projects/github/mvn_scalafmt/pom.xml, line 5, column 17
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] Inspecting build with total of 1 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 1 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[INFO] 
[INFO] ------------------< org.antipathy:mvn-scalafmt_2.12 >-------------------
[INFO] Building ScalaFmt Maven Plugin (2.12) 1.0.2-SNAPSHOT
[INFO] ----------------------------[ maven-plugin ]----------------------------
[INFO] 
[INFO] --- mvn-scalafmt_2.12:1.0.2-SNAPSHOT:format (default-cli) @ mvn-scalafmt_2.12 ---
[ERROR] 
org.scalafmt.dynamic.exceptions.ScalafmtException: missing setting 'version'. To fix this problem, add the following line to .scalafmt.conf: 'version=2.0.1'.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.871 s
[INFO] Finished at: 2019-10-13T21:23:17-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.antipathy:mvn-scalafmt_2.12:1.0.2-SNAPSHOT:format (default-cli) on project mvn-scalafmt_2.12: Error formatting Scala files: missing setting 'version'. To fix this problem, add the following line to .scalafmt.conf: 'version=2.0.1'. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

I can add some scalatests if this solution looks acceptable

Fixes # (issue)
#42 
## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Tested manually
### To Reproduce
0. Checkout this project, master branch
1. Make `.scalafmt.conf` invalid in some way (e.g.add a space inside of one of the rule names)
2. Run `mvn org.antipathy:mvn-scalafmt_2.12:format`
3. Observe errors in logs and successful build message at the end

### To Test the Fix
0. Checkout this project, fix branch
1. mvn clean install
1. Make `.scalafmt.conf` invalid in some way (e.g.add a space inside of one of the rule names)
2. Change version to the the one just installed (1.0.2-SNAPSHOT)
2. Run `mvn org.antipathy:mvn-scalafmt_2.12:format`
3. Observe errors in logs and error build message at the end
 
**Test Configuration**:
* Firmware version: Linux Mint 18.1
* SDK: 
```java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)
```

# Checklist:

- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by jozic** [comment]
@SimonJPegg do you mind checking this out?

**Comment by SimonJPegg** [comment]
Thanks for the PR dude.  Not keen on the `var` usage though.  Couldn't we solve this with a private method  on the `ScalaFormatter` companion object?

```scala
private def validateVersion(configPath : Path, respectVersion: Boolean) : Unit = {
    val noVersion = Try {
      ConfigFactory.parseFile(configPath.toFile).getString("version")
    }.getOrElse("").isEmpty
    if (respectVersion && noVersion ) {
      throw new MojoExecutionException("No version found in config file and respectVersion = true")
    }
  }
```

and update the `apply` method to 

```scala
def apply(configLocation: String, log: Log, respectVersion: Boolean, testOnly: Boolean): ScalaFormatter = {
    val config        = LocalConfigBuilder(log).build(configLocation)
    validateVersion(config,respectVersion)
    val sourceBuilder = new SourceFileSequenceBuilder(log)
    val scalafmt = Scalafmt
      .create(this.getClass.getClassLoader)
      .withReporter(new MavenLogReporter(log))
      .withRespectVersion(respectVersion)
    val sourceFormatter = new SourceFileFormatter(config, scalafmt, log)
    val fileWriter = if (testOnly) {
      new TestResultLogWriter(log)
    } else {
      new FormattedFilesWriter(log)
    }
    new ScalaFormatter(sourceBuilder, sourceFormatter, fileWriter)
  }
```

**Comment by jozic** [comment]
This will solve the issue with missing version, but not other issues with config
Like I mentioned in reproducing scenario, try to add a space inside of one of the rule names
Scalafmt will emit errors, but the build will be successful.
I think with current interface that Scalafmt provides, spying on logger is the only way (as this is where errors are reported). And I can't think of any other solutions except using a var (not a fan of it either, but i don't have a better idea)
wdyt?

**Comment by SimonJPegg** [comment]
What about just throwing the exception in the logger when the `error` method is called?

**Comment by jozic** [comment]
Yep, that's what sbt plugin does. The only "downside" of that is that it will fail on the first error. So if one has many errors, they will have to fix them one by one. But I can change it to exception, this still would be better than fake "success"
I will give it a try soon

**Comment by jozic** [comment]
@SimonJPegg updated it to throw exception and I think i like it even better now
Codacy is not happy about me using `null`, which i can replace with new RuntimeException without a message if needed
not sure about Travis though, as its failure seems unrelated
```
The command "echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import" failed and exited with 127 during .
```

**Comment by jozic** [comment]
also this fixes #44

**Review by SimonJPegg — APPROVED** [review]

**Comment by jozic** [comment]
thanks for quick release!

**Pull request merged**
