### PR TITLE
 Upgrade to Scalafmt 1.5.1 and all other libs

### PR DESCRIPTION
**Pull request by joan38**

### CODE REVIEW

**Comment by SimonJPegg** [comment]
LGTM

**Comment by joan38** [comment]
Thanks @SimonJPegg
Do you know when this will get released?

**Comment by SimonJPegg** [comment]
Should be up now, you'll need to specify which version of Scala you're using from now on though. So
`<artifactId>mvn-scalafmt_2.11</artifactId>` or `<artifactId>mvn-scalafmt_2.12</artifactId>`

**Comment by joan38** [comment]
Perfect it works like a charm.
Thanks @SimonJPegg

**Pull request merged**
