### PR TITLE
Support using repositories project configuration for dynamic scalafmt loading

### PR DESCRIPTION
**Pull request by NoamShaish**
# Description

When working behind proxy the dynamic loading of the scalafmt will fail.
In some cases the organisation might have a mirror of maven central that can be used.
This PR enables the user to indicate the maven repositories to be by scalafmt dynamic loading.

Fixes # (issue)
https://github.com/SimonJPegg/mvn_scalafmt/issues/49

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

I have created a local instance of the plugin and run once behind proxy seeing it fails, when setting the new property to true the call was successful

### CODE REVIEW

**Comment by SimonJPegg** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/main/java/org/antipathy/mvn_scalafmt/FormatMojo.java  1
- src/main/scala/org/antipathy/mvn_scalafmt/ScalaFormatter.scala  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Antipathy_org/mvn_scalafmt/pullRequest?prid=5393354&bid=17680019)

**Comment by SimonJPegg** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/main/java/org/antipathy/mvn_scalafmt/FormatMojo.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Antipathy_org/mvn_scalafmt/pullRequest?prid=5393354&bid=17680019)

**Comment by SimonJPegg** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/main/java/org/antipathy/mvn_scalafmt/FormatMojo.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Antipathy_org/mvn_scalafmt/pullRequest?prid=5393354&bid=17680019)

**Comment by NoamShaish** [comment]
@SimonJPegg could you please review this PR

**Review by SimonJPegg — APPROVED** [review]

**Comment by SimonJPegg** [comment]
Thanks for this.

**Pull request merged**
